# Generated by Django 3.1.2 on 2023-05-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20230522_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ad',
            name='meta_title',
            field=models.TextField(default=''),
        ),
    ]
