# Generated by Django 3.1.2 on 2023-05-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20230522_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.CharField(default='2JK5K701HF', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
