# Generated by Django 3.1.2 on 2023-05-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20230522_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.CharField(default='XJH4030OT0', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='ads.state'),
        ),
    ]
