# Generated by Django 3.1.2 on 2023-05-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_auto_20230526_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='locality',
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.CharField(default='YGSS25FCRO', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Locality',
        ),
    ]
