# Generated by Django 3.1.2 on 2023-05-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_auto_20230526_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='user',
        ),
        migrations.AddField(
            model_name='agency',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.CharField(default='EGUE6FCNC8', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='agency',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
