# Generated by Django 3.1.2 on 2023-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_auto_20230526_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.CharField(default='Y7GJWX7RGA', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
