# Generated by Django 3.1.2 on 2023-05-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_auto_20230526_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.CharField(default='QPI41HZE7M', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
