# Generated by Django 3.1.2 on 2023-05-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_auto_20230527_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.CharField(default='OVEZC49FQ1', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
