# Generated by Django 3.1.2 on 2023-05-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_auto_20230527_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.CharField(default='SLNKXBXNU4', max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
