# Generated by Django 3.2.19 on 2023-06-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0028_auto_20230529_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='page_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
