# Generated by Django 3.0 on 2023-06-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0032_auto_20230602_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='categories',
            field=models.ManyToManyField(blank=True, to='ads.Category'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='images',
            field=models.ManyToManyField(blank=True, to='ads.Image'),
        ),
    ]
