# Generated by Django 3.0 on 2023-06-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0033_auto_20230602_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['city', 'slug'], name='ads_ad_city_id_f78a38_idx'),
        ),
    ]
