# Generated by Django 3.0 on 2023-06-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0034_auto_20230602_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name_plural': 'Ads'},
        ),
        migrations.RemoveIndex(
            model_name='ad',
            name='ads_ad_city_id_f78a38_idx',
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['city', 'profile_status'], name='ads_ad_city_id_256bde_idx'),
        ),
    ]
