# Generated by Django 3.0 on 2023-06-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0035_auto_20230602_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='get_no_of_cg_ads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='get_no_of_es_ads',
            field=models.IntegerField(default=0),
        ),
    ]
