# Generated by Django 4.2.1 on 2023-06-03 08:54

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0037_auto_20230603_1112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="thumbnail",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                blank=True,
                breakpoints={"l": 1200, "m": 992, "s": 768, "xl": 1400, "xs": 576},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                null=True,
                pixel_densities=[1, 2],
                upload_to="",
            ),
        ),
    ]
