# Generated by Django 3.2.8 on 2023-06-05 07:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0038_alter_ad_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
