# Generated by Django 3.2.8 on 2023-06-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0040_auto_20230605_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='page_content',
            new_name='call_girl_page_content',
        ),
    ]
