# Generated by Django 3.2.8 on 2023-06-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0042_auto_20230607_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.CharField(default='rds0752', max_length=100),
        ),
    ]
