# Generated by Django 3.2.8 on 2023-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0044_city_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='rank',
        ),
        migrations.AddField(
            model_name='ad',
            name='rank',
            field=models.IntegerField(default=10),
        ),
    ]
