# Generated by Django 2.2 on 2023-06-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
