# Generated by Django 3.0 on 2023-06-02 07:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230601_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
