# Generated by Django 3.0 on 2023-06-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230602_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['key'], name='home_data_key_a177e5_idx'),
        ),
    ]
