# Generated by Django 3.0 on 2023-06-02 11:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='position',
            field=models.CharField(blank=True, choices=[('Top', 'Top'), ('Bottom', 'Bottom')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='content'),
        ),
    ]
